import Head from 'next/head'
import Filter from '../components/Filter/Filter'
import JobList from '../components/JobList/JobList'
import Nav from '../components/Nav/Nav'
import Search from '../components/Search/Search'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-indigo-50 pb-5">
        <Nav />
        <Search />
      </header>
      <div className="md:flex mt-12 mx-4 sm:mx-8">
        <Filter />
        <JobList />
      </div>
    </div>
  )
}